<?php

namespace Database\Seeders;

use App\Models\CardTemplate;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CardTemplateSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $templates = [
            [
                'name' => 'مقهى الورد',
                'title' => 'كوبك مكافأة',
                'description' => 'احصل على كوب مجاني بعد شراء 8 أكواب',
                'bg_color' => '#8B4513',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 0,
                'total_stages' => 8,
                'active_stamp_type' => 'Coffee',
                'inactive_stamp_type' => 'Coffee',
                'card_description' => 'اجمع الأختام واحصل على كوب قهوة مجاني ☕',
                'how_to_earn' => 'احصل على ختم واحد مع كل كوب قهوة تشتريه',
                'company_name' => 'مقهى الورد',
                'terms_of_use' => "1. احصل على ختم واحد مع كل كوب قهوة.\n2. اجمع 8 أختام للحصول على كوب مجاني.\n3. البطاقة صالحة لمدة سنة واحدة.",
                'source_company_name' => 'مقهى الورد',
                'source_email' => 'info@cafe-ward.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#8B4513',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#FF6B35',
                    'stampBackground' => '#F5E6D3',
                    'borderColor' => '#8B4513',
                    'inactiveStamp' => '#D3C5B0',
                ],
            ],
            [
                'name' => 'صالون السيارات',
                'title' => 'لمعان وسرعة',
                'description' => 'احصل على خدمة مجانية بعد 4 زيارات',
                'bg_color' => '#2196F3',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 0,
                'total_stages' => 4,
                'active_stamp_type' => 'Car',
                'inactive_stamp_type' => 'Car',
                'card_description' => 'اعتن بسيارتك واحصل على مكافآت 🚗',
                'how_to_earn' => 'احصل على ختم مع كل خدمة غسيل أو تلميع',
                'company_name' => 'صالون السيارات',
                'terms_of_use' => "1. احصل على ختم مع كل خدمة.\n2. اجمع 4 أختام للحصول على خدمة مجانية.\n3. الصلاحية سنة واحدة.",
                'source_company_name' => 'صالون السيارات',
                'source_email' => 'info@car-salon.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#2196F3',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#03A9F4',
                    'stampBackground' => '#BBDEFB',
                    'borderColor' => '#2196F3',
                    'inactiveStamp' => '#90CAF9',
                ],
            ],
            [
                'name' => 'مكتبة المعرفة',
                'title' => 'اقرأ وتعلم',
                'description' => 'احصل على كتاب مجاني بعد 6 مشتريات',
                'bg_color' => '#795548',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 0,
                'total_stages' => 6,
                'active_stamp_type' => 'Star',
                'inactive_stamp_type' => 'Star',
                'card_description' => 'ابني مكتبتك واحصل على مكافآت 📚',
                'how_to_earn' => 'احصل على ختم مع كل كتاب أو منتج تشتريه',
                'company_name' => 'مكتبة المعرفة',
                'terms_of_use' => "1. احصل على ختم مع كل شراء.\n2. اجمع 6 أختام للحصول على كتاب مجاني.\n3. البطاقة صالحة لمدة سنتين.",
                'source_company_name' => 'مكتبة المعرفة',
                'source_email' => 'info@bookstore.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#795548',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#FF9800',
                    'stampBackground' => '#D7CCC8',
                    'borderColor' => '#795548',
                    'inactiveStamp' => '#BCAAA4',
                ],
            ],
            [
                'name' => 'متحف الفنون',
                'title' => 'ثقافة ومكافأة',
                'description' => 'ادخل مجاناً بعد 3 زيارات',
                'bg_color' => '#607D8B',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 0,
                'total_stages' => 3,
                'active_stamp_type' => 'Crown',
                'inactive_stamp_type' => 'Crown',
                'card_description' => 'استكشف الفنون واحصل على مكافآت 🎨',
                'how_to_earn' => 'احصل على ختم مع كل زيارة للمتحف',
                'company_name' => 'متحف الفنون',
                'terms_of_use' => "1. احصل على ختم مع كل زيارة.\n2. اجمع 3 أختام للحصول على دخول مجاني.\n3. الصلاحية غير محدودة.",
                'source_company_name' => 'متحف الفنون',
                'source_email' => 'info@museum.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#607D8B',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#FFC107',
                    'stampBackground' => '#CFD8DC',
                    'borderColor' => '#607D8B',
                    'inactiveStamp' => '#90A4AE',
                ],
            ],
            [
                'name' => 'مكتبة الألعاب',
                'title' => 'لعب ومتعة',
                'description' => 'احصل على لعبة مجانية بعد 7 مشتريات',
                'bg_color' => '#FF9800',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1606166186675-c1c48b91be72?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 0,
                'total_stages' => 7,
                'active_stamp_type' => 'Gift',
                'inactive_stamp_type' => 'Gift',
                'card_description' => 'استمتع بالألعاب واحصل على مكافآت 🎮',
                'how_to_earn' => 'احصل على ختم مع كل لعبة أو منتج تشتريه',
                'company_name' => 'مكتبة الألعاب',
                'terms_of_use' => "1. احصل على ختم مع كل شراء.\n2. اجمع 7 أختام للحصول على لعبة مجانية.\n3. الصلاحية سنة واحدة.",
                'source_company_name' => 'مكتبة الألعاب',
                'source_email' => 'info@games-store.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#FF9800',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#FF5722',
                    'stampBackground' => '#FFE0B2',
                    'borderColor' => '#FF9800',
                    'inactiveStamp' => '#FFCC80',
                ],
            ],
            [
                'name' => 'صالون الحلاقة',
                'title' => 'أناقة مميزة',
                'description' => 'احصل على حلاقة مجانية بعد 5 زيارات',
                'bg_color' => '#1E324A',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 0,
                'total_stages' => 5,
                'active_stamp_type' => 'Crown',
                'inactive_stamp_type' => 'Crown',
                'card_description' => 'حافظ على أناقتك واحصل على مكافآت ✂️',
                'how_to_earn' => 'احصل على ختم مع كل حلاقة أو خدمة',
                'company_name' => 'صالون الحلاقة',
                'terms_of_use' => "1. احصل على ختم مع كل خدمة.\n2. اجمع 5 أختام للحصول على حلاقة مجانية.\n3. البطاقة صالحة لمدة سنة.",
                'source_company_name' => 'صالون الحلاقة',
                'source_email' => 'info@barbershop.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#1E324A',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#FFD700',
                    'stampBackground' => '#E8E8E8',
                    'borderColor' => '#1E324A',
                    'inactiveStamp' => '#CCCCCC',
                ],
            ],
            [
                'name' => 'مطعم البيتزا',
                'title' => 'بيتزا ومكافأة',
                'description' => 'احصل على بيتزا مجانية بعد 8 طلبات',
                'bg_color' => '#F44336',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 0,
                'total_stages' => 8,
                'active_stamp_type' => 'Heart',
                'inactive_stamp_type' => 'Heart',
                'card_description' => 'استمتع بأفضل بيتزا واحصل على مكافآت 🍕',
                'how_to_earn' => 'احصل على ختم مع كل بيتزا تشتريها',
                'company_name' => 'مطعم البيتزا',
                'terms_of_use' => "1. احصل على ختم مع كل بيتزا.\n2. اجمع 8 أختام للحصول على بيتزا مجانية.\n3. الصلاحية سنة واحدة.",
                'source_company_name' => 'مطعم البيتزا',
                'source_email' => 'info@pizza.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#F44336',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#FF5722',
                    'stampBackground' => '#FFCDD2',
                    'borderColor' => '#F44336',
                    'inactiveStamp' => '#EF9A9A',
                ],
            ],
            [
                'name' => 'مخبز الطازج',
                'title' => 'طازج ومكافأة',
                'description' => 'احصل على منتج مجاني بعد 6 مشتريات',
                'bg_color' => '#FFC107',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop',
                'text_color' => '#000000',
                'card_type' => 0,
                'total_stages' => 6,
                'active_stamp_type' => 'Star',
                'inactive_stamp_type' => 'Star',
                'card_description' => 'استمتع بمنتجات طازجة واحصل على مكافآت 🥖',
                'how_to_earn' => 'احصل على ختم مع كل عملية شراء بقيمة 20 ريال أو أكثر',
                'company_name' => 'مخبز الطازج',
                'terms_of_use' => "1. الحد الأدنى للشراء 20 ريال.\n2. اجمع 6 أختام للحصول على منتج مجاني.\n3. البطاقة صالحة لمدة سنة.",
                'source_company_name' => 'مخبز الطازج',
                'source_email' => 'info@bakery.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#FFC107',
                    'textColor' => '#000000',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#FF9800',
                    'stampBackground' => '#FFF9C4',
                    'borderColor' => '#000000',
                    'inactiveStamp' => '#FFF59D',
                ],
            ],
            [
                'name' => 'صالون التدليك',
                'title' => 'استرخاء ومكافأة',
                'description' => 'احصل على جلسة مجانية بعد 4 زيارات',
                'bg_color' => '#8BC34A',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 0,
                'total_stages' => 4,
                'active_stamp_type' => 'Heart',
                'inactive_stamp_type' => 'Heart',
                'card_description' => 'استرخ واستمتع واحصل على مكافآت 💆',
                'how_to_earn' => 'احصل على ختم مع كل جلسة تدليك',
                'company_name' => 'صالون التدليك',
                'terms_of_use' => "1. احصل على ختم مع كل جلسة.\n2. اجمع 4 أختام للحصول على جلسة مجانية.\n3. الصلاحية سنة واحدة.",
                'source_company_name' => 'صالون التدليك',
                'source_email' => 'info@spa.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#8BC34A',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#4CAF50',
                    'stampBackground' => '#DCEDC8',
                    'borderColor' => '#8BC34A',
                    'inactiveStamp' => '#AED581',
                ],
            ],
            [
                'name' => 'متجر الإلكترونيات',
                'title' => 'تكنولوجيا ومكافأة',
                'description' => 'استرداد نقدي 3% على كل عملية شراء',
                'bg_color' => '#00BCD4',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 1,
                'total_stages' => 0,
                'active_stamp_type' => 'Star',
                'inactive_stamp_type' => 'Star',
                'card_description' => 'تسوق التكنولوجيا واسترد نقداً 💻',
                'how_to_earn' => 'احصل على 3% استرداد نقدي على كل عملية شراء',
                'company_name' => 'متجر الإلكترونيات',
                'terms_of_use' => "1. استرداد نقدي 3% على كل عملية.\n2. يمكن سحب المبلغ عند الوصول إلى 100 ريال.\n3. البطاقة صالحة لمدة سنتين.",
                'source_company_name' => 'متجر الإلكترونيات',
                'source_email' => 'info@electronics.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#00BCD4',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#0097A7',
                    'stampBackground' => '#B2EBF2',
                    'borderColor' => '#00BCD4',
                    'inactiveStamp' => '#4DD0E1',
                ],
            ],
            [
                'name' => 'مطعم الحلويات',
                'title' => 'حلاوة ومكافأة',
                'description' => 'احصل على قطعة مجانية بعد 5 مشتريات',
                'bg_color' => '#E91E63',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 0,
                'total_stages' => 5,
                'active_stamp_type' => 'Gift',
                'inactive_stamp_type' => 'Gift',
                'card_description' => 'استمتع بأطيب الحلويات واحصل على مكافآت 🍰',
                'how_to_earn' => 'احصل على ختم مع كل قطعة حلويات',
                'company_name' => 'مطعم الحلويات',
                'terms_of_use' => "1. احصل على ختم مع كل شراء.\n2. اجمع 5 أختام للحصول على قطعة مجانية.\n3. الصلاحية سنة واحدة.",
                'source_company_name' => 'مطعم الحلويات',
                'source_email' => 'info@desserts.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#E91E63',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#F06292',
                    'stampBackground' => '#F8BBD0',
                    'borderColor' => '#E91E63',
                    'inactiveStamp' => '#F48FB1',
                ],
            ],
            [
                'name' => 'صالون الأظافر',
                'title' => 'جمال ومكافأة',
                'description' => 'احصل على خدمة مجانية بعد 6 زيارات',
                'bg_color' => '#9C27B0',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 0,
                'total_stages' => 6,
                'active_stamp_type' => 'Heart',
                'inactive_stamp_type' => 'Heart',
                'card_description' => 'اهتمي بأظافرك واحصلي على مكافآت 💅',
                'how_to_earn' => 'احصلي على ختم مع كل خدمة أظافر',
                'company_name' => 'صالون الأظافر',
                'terms_of_use' => "1. احصلي على ختم مع كل خدمة.\n2. اجمعي 6 أختام للحصول على خدمة مجانية.\n3. البطاقة صالحة لمدة سنة.",
                'source_company_name' => 'صالون الأظافر',
                'source_email' => 'info@nail-salon.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#9C27B0',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#E91E63',
                    'stampBackground' => '#F3E5F5',
                    'borderColor' => '#9C27B0',
                    'inactiveStamp' => '#CE93D8',
                ],
            ],
            [
                'name' => 'مطعم السوشي',
                'title' => 'ياباني أصيل',
                'description' => 'احصل على وجبة مجانية بعد 9 طلبات',
                'bg_color' => '#3F51B5',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 0,
                'total_stages' => 9,
                'active_stamp_type' => 'Star',
                'inactive_stamp_type' => 'Star',
                'card_description' => 'استمتع بأفضل سوشي واحصل على مكافآت 🍣',
                'how_to_earn' => 'احصل على ختم مع كل طلب بقيمة 80 ريال أو أكثر',
                'company_name' => 'مطعم السوشي',
                'terms_of_use' => "1. الحد الأدنى للطلب 80 ريال.\n2. اجمع 9 أختام للحصول على وجبة مجانية.\n3. الصلاحية سنة واحدة.",
                'source_company_name' => 'مطعم السوشي',
                'source_email' => 'info@sushi.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#3F51B5',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#5C6BC0',
                    'stampBackground' => '#C5CAE9',
                    'borderColor' => '#3F51B5',
                    'inactiveStamp' => '#9FA8DA',
                ],
            ],
            [
                'name' => 'مكتبة الألعاب الإلكترونية',
                'title' => 'لعب وادخر',
                'description' => 'استرداد نقدي 5% على كل لعبة',
                'bg_color' => '#FF6B35',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 1,
                'total_stages' => 0,
                'active_stamp_type' => 'Star',
                'inactive_stamp_type' => 'Star',
                'card_description' => 'اشتري الألعاب واسترد نقداً 🎮',
                'how_to_earn' => 'احصل على 5% استرداد نقدي على كل لعبة تشتريها',
                'company_name' => 'مكتبة الألعاب الإلكترونية',
                'terms_of_use' => "1. استرداد نقدي 5% على كل لعبة.\n2. يمكن سحب المبلغ عند الوصول إلى 50 ريال.\n3. البطاقة صالحة لمدة سنتين.",
                'source_company_name' => 'مكتبة الألعاب الإلكترونية',
                'source_email' => 'info@games-store.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#FF6B35',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#FF8C42',
                    'stampBackground' => '#FFE5D9',
                    'borderColor' => '#FF6B35',
                    'inactiveStamp' => '#FFBFA0',
                ],
            ],
            [
                'name' => 'مطعم البرجر',
                'title' => 'برجر ومكافأة',
                'description' => 'احصل على برجر مجاني بعد 7 طلبات',
                'bg_color' => '#D32F2F',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 0,
                'total_stages' => 7,
                'active_stamp_type' => 'Plane',
                'inactive_stamp_type' => 'Plane',
                'card_description' => 'استمتع بأطيب البرجر واحصل على مكافآت 🍔',
                'how_to_earn' => 'احصل على ختم مع كل برجر تشتريه',
                'company_name' => 'مطعم البرجر',
                'terms_of_use' => "1. احصل على ختم مع كل برجر.\n2. اجمع 7 أختام للحصول على برجر مجاني.\n3. الصلاحية سنة واحدة.",
                'source_company_name' => 'مطعم البرجر',
                'source_email' => 'info@burger.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#D32F2F',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#F44336',
                    'stampBackground' => '#FFCDD2',
                    'borderColor' => '#D32F2F',
                    'inactiveStamp' => '#EF9A9A',
                ],
            ],
            [
                'name' => 'صالون الجمال',
                'title' => 'تجميل مميز',
                'description' => 'احصل على جلسة مجانية بعد 5 زيارات',
                'bg_color' => '#E91E63',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 0,
                'total_stages' => 5,
                'active_stamp_type' => 'Heart',
                'inactive_stamp_type' => 'Heart',
                'card_description' => 'اعتن بجمالك واحصل على مكافآت حصرية 💄',
                'how_to_earn' => 'احصل على ختم عند كل زيارة أو خدمة',
                'company_name' => 'صالون الجمال',
                'terms_of_use' => "1. احصل على ختم واحد مع كل خدمة.\n2. اجمع 5 أختام للحصول على جلسة مجانية.\n3. الصلاحية غير محدودة.",
                'source_company_name' => 'صالون الجمال',
                'source_email' => 'info@beauty-salon.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#E91E63',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#FF1744',
                    'stampBackground' => '#FCE4EC',
                    'borderColor' => '#E91E63',
                    'inactiveStamp' => '#F8BBD0',
                ],
            ],
            [
                'name' => 'مطعم الذواقة',
                'title' => 'طعم ومكافأة',
                'description' => 'احصل على وجبة مجانية بعد 10 وجبات',
                'bg_color' => '#FF5722',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 0,
                'total_stages' => 10,
                'active_stamp_type' => 'Gift',
                'inactive_stamp_type' => 'Gift',
                'card_description' => 'استمتع بأطيب المأكولات واحصل على مكافآت 🍽️',
                'how_to_earn' => 'احصل على ختم مع كل وجبة بقيمة 50 ريال أو أكثر',
                'company_name' => 'مطعم الذواقة',
                'terms_of_use' => "1. الحد الأدنى للطلب 50 ريال.\n2. اجمع 10 أختام للحصول على وجبة مجانية.\n3. الصلاحية سنة واحدة.",
                'source_company_name' => 'مطعم الذواقة',
                'source_email' => 'info@restaurant.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#FF5722',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#FF9800',
                    'stampBackground' => '#FFE0B2',
                    'borderColor' => '#FF5722',
                    'inactiveStamp' => '#FFCCBC',
                ],
            ],
            [
                'name' => 'نادي اللياقة',
                'title' => 'تمرين وادخر',
                'description' => 'احصل على شهر مجاني بعد 6 أشهر',
                'bg_color' => '#009688',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 0,
                'total_stages' => 6,
                'active_stamp_type' => 'Trophy',
                'inactive_stamp_type' => 'Trophy',
                'card_description' => 'حافظ على لياقتك واحصل على مكافآت 🏋️',
                'how_to_earn' => 'احصل على ختم مع كل شهر اشتراك',
                'company_name' => 'نادي اللياقة',
                'terms_of_use' => "1. احصل على ختم مع كل شهر اشتراك.\n2. اجمع 6 أختام للحصول على شهر مجاني.\n3. غير قابل للتحويل.",
                'source_company_name' => 'نادي اللياقة',
                'source_email' => 'info@gym.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#009688',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#00BCD4',
                    'stampBackground' => '#B2DFDB',
                    'borderColor' => '#009688',
                    'inactiveStamp' => '#80CBC4',
                ],
            ],
            [
                'name' => 'متجر الأزياء',
                'title' => 'موضة ومكافأة',
                'description' => 'احصل على خصم 20% بعد 5 عمليات شراء',
                'bg_color' => '#9C27B0',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 0,
                'total_stages' => 5,
                'active_stamp_type' => 'ShoppingBag',
                'inactive_stamp_type' => 'ShoppingBag',
                'card_description' => 'تسوق بذوق واحصل على مكافآت 👗',
                'how_to_earn' => 'احصل على ختم مع كل عملية شراء بقيمة 100 ريال أو أكثر',
                'company_name' => 'متجر الأزياء',
                'terms_of_use' => "1. الحد الأدنى للشراء 100 ريال.\n2. اجمع 5 أختام للحصول على خصم 20%.\n3. الصلاحية غير محدودة.",
                'source_company_name' => 'متجر الأزياء',
                'source_email' => 'info@fashion-store.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#9C27B0',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#E91E63',
                    'stampBackground' => '#F3E5F5',
                    'borderColor' => '#9C27B0',
                    'inactiveStamp' => '#CE93D8',
                ],
            ],
            [
                'name' => 'سوبر ماركت الوفير',
                'title' => 'ادخر واربح',
                'description' => 'استرداد نقدي 2% على كل عملية شراء',
                'bg_color' => '#4CAF50',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 1,
                'total_stages' => 1,
                'active_stamp_type' => 'Star',
                'inactive_stamp_type' => 'Star',
                'card_description' => 'اكسب استرداد نقدي على كل عملية شراء 🛒',
                'how_to_earn' => 'استرداد 2% على كل عملية شراء فوق 200 ريال',
                'company_name' => 'سوبر ماركت الوفير',
                'terms_of_use' => "1. الاسترداد يتم على المشتريات فوق 200 ريال.\n2. يمكن استبدال الرصيد في أي وقت.\n3. الرصيد غير قابل للتحويل.",
                'source_company_name' => 'سوبر ماركت الوفير',
                'source_email' => 'info@alwafir.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#4CAF50',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#8BC34A',
                    'stampBackground' => '#E8F5E9',
                    'borderColor' => '#4CAF50',
                    'inactiveStamp' => '#C8E6C9',
                ],
            ],
            [
                'name' => 'مغسلة السيارات',
                'title' => 'نظافة ومكافأة',
                'description' => 'غسيل مجاني بعد 6 زيارات',
                'bg_color' => '#1E324A',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 0,
                'total_stages' => 6,
                'active_stamp_type' => 'Car',
                'inactive_stamp_type' => 'Car',
                'card_description' => 'حافظ على سيارتك نظيفة مع مكافآت 🚗',
                'how_to_earn' => 'احصل على ختم عند كل غسيل كامل',
                'company_name' => 'مغسلة السيارات',
                'terms_of_use' => "1. احصل على ختم مع كل غسيل كامل.\n2. اجمع 6 أختام للحصول على غسيل مجاني.\n3. غير قابل للتحويل.",
                'source_company_name' => 'مغسلة سيارات الرياض',
                'source_email' => 'info@wash.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#1E324A',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#3498DB',
                    'stampBackground' => '#E3F2FD',
                    'borderColor' => '#1E324A',
                    'inactiveStamp' => '#90CAF9',
                ],
            ],
            [
                'name' => 'مكتبة القراءة',
                'title' => 'اقرأ واربح',
                'description' => 'كتاب مجاني بعد 8 مشتريات',
                'bg_color' => '#3E2723',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e6?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 0,
                'total_stages' => 8,
                'active_stamp_type' => 'Star',
                'inactive_stamp_type' => 'Star',
                'card_description' => 'ازداد معرفة واحصل على مكافآت 📚',
                'how_to_earn' => 'احصل على ختم لكل كتاب بقيمة 80 ريال أو أكثر',
                'company_name' => 'مكتبة القراءة',
                'terms_of_use' => "1. الحد الأدنى لشراء الكتاب 80 ريال.\n2. اجمع 8 أختام للحصول على كتاب مجاني.\n3. الصلاحية غير محدودة.",
                'source_company_name' => 'مكتبة القراءة',
                'source_email' => 'info@reading-library.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#3E2723',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#795548',
                    'stampBackground' => '#EFEBE9',
                    'borderColor' => '#3E2723',
                    'inactiveStamp' => '#D7CCC8',
                ],
            ],
            [
                'name' => 'مركز السبا',
                'title' => 'استرخِ واحصل على مكافأة',
                'description' => 'جلسة مجانية بعد 4 جلسات',
                'bg_color' => '#5D4037',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 0,
                'total_stages' => 4,
                'active_stamp_type' => 'Heart',
                'inactive_stamp_type' => 'Heart',
                'card_description' => 'دلل نفسك وعود للحصول على جلسة مجانية 💆',
                'how_to_earn' => 'احصل على ختم عند كل جلسة تدليك أو عناية بالبشرة',
                'company_name' => 'مركز السبا',
                'terms_of_use' => "1. احصل على ختم لكل جلسة.\n2. اجمع 4 أختام للحصول على جلسة مجانية.\n3. لا يمكن تحويل الجلسات.",
                'source_company_name' => 'مركز السبا',
                'source_email' => 'info@spa-center.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#5D4037',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#FFAB91',
                    'stampBackground' => '#FBE9E7',
                    'borderColor' => '#5D4037',
                    'inactiveStamp' => '#FFCCBC',
                ],
            ],
            [
                'name' => 'مخبز صباح الخير',
                'title' => 'خبز ومكافأة',
                'description' => 'صندوق حلويات مجاني بعد 7 مشتريات',
                'bg_color' => '#D84315',
                'bg_opacity' => 0.9,
                'bg_image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop',
                'text_color' => '#FFFFFF',
                'card_type' => 0,
                'total_stages' => 7,
                'active_stamp_type' => 'Gift',
                'inactive_stamp_type' => 'Gift',
                'card_description' => 'دلل نفسك بمذاق الحلويات 🍞',
                'how_to_earn' => 'احصل على ختم لكل فاتورة بقيمة 30 ريال أو أكثر',
                'company_name' => 'مخبز صباح الخير',
                'terms_of_use' => "1. الحد الأدنى للفاتورة 30 ريال.\n2. اجمع 7 أختام لصندوق حلويات مجاني.\n3. الصلاحية 6 أشهر.",
                'source_company_name' => 'مخبز صباح الخير',
                'source_email' => 'info@bakery.com',
                'phone_number' => '547669684',
                'country_code' => '+966',
                'colors' => [
                    'backgroundColor' => '#D84315',
                    'textColor' => '#FFFFFF',
                    'middleAreaBg' => '#FFFFFF',
                    'activeStamp' => '#FF7043',
                    'stampBackground' => '#FFCCBC',
                    'borderColor' => '#BF360C',
                    'inactiveStamp' => '#FFAB91',
                ],
            ],
        ];

        foreach ($templates as $template) {
            CardTemplate::updateOrCreate(
                ['name' => $template['name']],
                $template
            );
        }
    }
}
